# MkDocs Configuration for Claude Agent SDK Documentation
site_name: Claude Agent SDK Documentation
site_description: Comprehensive guide to building AI agents with Claude Agent SDK
site_author: Community Contributors
site_url: https://Nucs.github.io/claude-code-python-sdk-unofficial-docs/

# Repository
repo_name: Nucs/claude-code-python-sdk-unofficial-docs
repo_url: https://github.com/Nucs/claude-code-python-sdk-unofficial-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Claude Agent SDK Community

# Theme Configuration
theme:
  name: material
  language: en

  # Color Palette - Dark mode focused
  palette:
    # Dark mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  # Fonts
  font:
    text: Roboto
    code: JetBrains Mono

  # Features - Working navigation
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

  # Logo and favicon
  icon:
    logo: material/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en

# Navigation - Simple and working
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Tools & MCP: tools-and-mcp.md
  - API Reference: api-reference.md
  - Real-World Use Cases: real-world-use-cases.md
  - Production Patterns: production-patterns.md
  - Security: security.md
  - Performance: performance-optimization.md
  - Troubleshooting: troubleshooting.md
  - Community: community-resources.md
  - References: references.md

# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Extra CSS/JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nucs/claude-code-python-sdk-unofficial-docs
  generator: false
