# MkDocs Configuration for Claude Agent SDK Documentation - Simple Working Version
site_name: Claude Agent SDK Documentation
site_description: Comprehensive guide to building AI agents with Claude Agent SDK
site_author: Community Contributors
site_url: https://Nucs.github.io/claude-code-python-sdk-unofficial-docs/

# Repository
repo_name: Nucs/claude-code-python-sdk-unofficial-docs
repo_url: https://github.com/Nucs/claude-code-python-sdk-unofficial-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Claude Agent SDK Community

# Theme Configuration
theme:
  name: material
  language: en

  # Color Palette
  palette:
    # Light mode
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

  # Features
  features:
    - navigation.instant      # Instant loading
    - navigation.tracking     # URL tracking
    - navigation.tabs         # Top-level tabs
    - navigation.tabs.sticky  # Sticky tabs
    - navigation.sections     # Section navigation
    - navigation.expand       # Expand sections
    - navigation.indexes      # Section index pages
    - navigation.top          # Back to top button
    - search.suggest          # Search suggestions
    - search.highlight        # Highlight search terms
    - content.tabs.link       # Link content tabs
    - content.code.copy       # Copy code button
    - toc.follow              # Follow TOC

  # Logo and favicon
  icon:
    logo: material/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en

# Navigation
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started:
    - Quick Start: getting-started.md
    - Installation: getting-started.md#installation
  - Core Concepts:
    - Architecture: architecture.md
    - Agent Loop: architecture.md#agent-loop
    - Tools & MCP: tools-and-mcp.md
  - API Reference:
    - Complete API: api-reference.md
    - Python SDK: api-reference.md#python-sdk
    - TypeScript SDK: api-reference.md#typescript-sdk
  - Real-World Examples:
    - Use Cases: real-world-use-cases.md
    - Enterprise: real-world-use-cases.md#enterprise-implementations
    - Open Source: real-world-use-cases.md#open-source-community-projects
  - Production:
    - Deployment Patterns: production-patterns.md
    - Security Best Practices: security.md
    - Performance Optimization: performance-optimization.md
  - Troubleshooting:
    - Common Issues: troubleshooting.md
    - FAQ: troubleshooting.md#common-issues
  - Community:
    - Resources: community-resources.md
    - Contributing: community-resources.md#contributing
    - References: references.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Extra CSS/JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nucs/claude-code-python-sdk-unofficial-docs
